from nourish_campus.models.models import MenuItem, Customer, Restaurant, MealOrder, OrderItem

from sqlalchemy import create_engine
from nourish_campus.extensions import db
from nourish_campus import create_app, bcrypt
from nourish_campus.models import *

from sqlalchemy.orm import Session

# create all the tables in models directory
db.create_all(app=create_app())

# initialize a db session
engine = create_engine('sqlite:///nourish_campus/db.sqlite3', echo=True)
db_session = Session(engine)

# Delete old data in the tables
db_session.query(Customer).delete()
db_session.query(Restaurant).delete()
db_session.query(MenuItem).delete()
db_session.query(MealOrder).delete()
db_session.query(OrderItem).delete()
db_session.commit()

# add customers
hashed_password = bcrypt.generate_password_hash("password").decode('utf-8')
customers = [
    Customer(username="jd101a", name="John Doe", password=hashed_password, daily_calories_goal=2800, email="jd101a@american.edu", per_meal_calories_limit=1000)
]
db_session.add_all(customers)
db_session.commit()

# add restaurant
restaurants = [
    Restaurant(name="Starbucks", phone="202-885-7497", email="123@mail.com", address="Mary Graydon Center Tunnel"),
    Restaurant(name="Subway", phone="202-237-2424", email="123@mail.com", address="Mary Graydon Center Tunnel")

]
db_session.add_all(restaurants)
db_session.commit()
# add menu items
menuItems = [
    MenuItem(name="Caffe Mocha", price=8.45, calories=370, restaurant_id=1),
    MenuItem(name="Cappuccino", price=7.95, calories=140, restaurant_id=1),
    MenuItem(name="Caffe Misto", price=4.45, calories=110, restaurant_id=1),
    MenuItem(name="Espresso Macchiato", price=7.55, calories=15, restaurant_id=1),
    MenuItem(name="Espresso", price=5.45, calories=10, restaurant_id=1),
    MenuItem(name="Honey Almondmilk Flat White", price=7.45, calories=170, restaurant_id=1),
    MenuItem(name="Caramel Macchiato", price=9.95, calories=250, restaurant_id=1),
    MenuItem(name="Caffe Americano", price=7.45, calories=15, restaurant_id=1),
    MenuItem(name="Honey Oatmilk Latte", price=8.45, calories=250, restaurant_id=1),
    MenuItem(name="Flat White", price=8.45, calories=220, restaurant_id=1),
    MenuItem(name="Espresso con Panna", price=5.85, calories=35, restaurant_id=1),
    MenuItem(name="Steamed Milk", price=4.65, calories=200, restaurant_id=1),
    MenuItem(name="Peppermint Hot Chocolate", price=4.75, calories=440, restaurant_id=1),
    MenuItem(name="Peppermint White Hot Chocolate", price=4.75, calories=520, restaurant_id=1),
    MenuItem(name="Blonde Vanilla Latte", price=8.65, calories=250, restaurant_id=1),
    MenuItem(name="Coffee", price=3.65, calories=5, restaurant_id=1),
    MenuItem(name="Iced Flat White", price=7.65, calories=150, restaurant_id=1),
    MenuItem(name="Iced Caramel Macchiato", price=9.95, calories=250, restaurant_id=1),
    MenuItem(name="Iced Honey Oatmilk Latte", price=7.25, calories=230, restaurant_id=1),
    MenuItem(name="Vanilla Sweet Cream Cold Brew", price=6.25, calories=110, restaurant_id=1),
    MenuItem(name="Cold Brew Coffee", price=4.95, calories=5, restaurant_id=1),
    MenuItem(name="Salted Caramel Cream Cold Brew", price=5.75, calories=240, restaurant_id=1),
    MenuItem(name="Honey Almondmilk Cold Brew", price=5.45, calories=55, restaurant_id=1),
    MenuItem(name="Iced Coffee", price=4.75, calories=80, restaurant_id=1),
    MenuItem(name="Iced White Chocolate Mocha", price=8.25, calories=390, restaurant_id=1),
    MenuItem(name="Iced Caffe Americano", price=7.15, calories=15, restaurant_id=1),
    MenuItem(name="Iced Cinnamon Dolce Latte", price=7.55, calories=300, restaurant_id=1),
    MenuItem(name="Iced Blonde Vanilla Latte", price=8.05, calories=190, restaurant_id=1),
    MenuItem(name="Iced Espresso con Panna", price=5.85, calories=35, restaurant_id=1),
    MenuItem(name="Iced Espresso", price=5.75, calories=10, restaurant_id=1),
    MenuItem(name="Chocolate Creme Cold Brew", price=5.45, calories=250, restaurant_id=1),
    MenuItem(name="Iced Caffe Latte", price=7.25, calories=130, restaurant_id=1),
    MenuItem(name="Iced Caffe Mocha", price=7.75, calories=350, restaurant_id=1),
    MenuItem(name="Iced Peppermint White Chocolate Mocha", price=4.75, calories=490, restaurant_id=1),
    MenuItem(name="Caramel Apple Spice", price=6.25, calories=380, restaurant_id=1),
    MenuItem(name="Hot Chocolate", price=6.65, calories=370, restaurant_id=1),
    MenuItem(name="White Hot Chocolate", price=7.05, calories=400, restaurant_id=1),
    MenuItem(name="Cinnamon Dolce Latte", price=6.55, calories=340, restaurant_id=1),
    MenuItem(name="Vanilla Creme", price=4.75, calories=350, restaurant_id=1),
    MenuItem(name="London Fog Tea Latte", price=8.05, calories=180, restaurant_id=1),
    MenuItem(name="Honey Citrus Mint Tea", price=4.75, calories=130, restaurant_id=1),
    MenuItem(name="Chai Tea Latte", price=6.25, calories=240, restaurant_id=1),
    MenuItem(name="Emperor's Clouds & Mist Tea", price=2.65, calories=0, restaurant_id=1),
    MenuItem(name="Matcha Green Tea Latte", price=11.75, calories=240, restaurant_id=1),
    MenuItem(name="Citrus Defender", price=3.75, calories=130, restaurant_id=1),
    MenuItem(name="Pink Drink", price=5.75, calories=140, restaurant_id=1),
    MenuItem(name="Dragon Drink", price=7.45, calories=130, restaurant_id=1),
    MenuItem(name="Mango Dragonfruit Refresher", price=6.25, calories=90, restaurant_id=1),
    MenuItem(name="Mango Dragonfruit Lemonade Refresher", price=7.75, calories=140, restaurant_id=1),
    MenuItem(name="Strawberry Acai Refresher", price=6.05, calories=100, restaurant_id=1),
    MenuItem(name="Strawberry Acai Lemonade Refresher", price=6.75, calories=140, restaurant_id=1),
    MenuItem(name="Pineapple Passionfruit Refresher", price=5.25, calories=100, restaurant_id=1),
    MenuItem(name="Pineapple Passionfruit Lemonade Refresher", price=5.75, calories=140, restaurant_id=1),
    MenuItem(name="Paradise Drink", price=5.75, calories=140, restaurant_id=1),
    MenuItem(name="Frozen Strawberry Acai Lemonade Refresher", price=7.85, calories=160, restaurant_id=1),
    MenuItem(name="Frozen Mango Dragonfruit Lemonade Refresher", price=7.85, calories=150, restaurant_id=1),
    MenuItem(name="Cinnamon Caramel Cream Cold Brew", price=6.50, calories=250, restaurant_id=1),
    MenuItem(name="Cinnamon Caramel Cream Nitro", price=7.00, calories=260, restaurant_id=1),
    MenuItem(name="Iced Matcha Green Tea Latte", price=9.25, calories=200, restaurant_id=1),
    MenuItem(name="Iced Chai Tea Latte", price=5.55, calories=240, restaurant_id=1),
    MenuItem(name="Iced Matcha Lemonade", price=5.75, calories=120, restaurant_id=1),
    MenuItem(name="Iced Black Tea Lemonade", price=4.95, calories=50, restaurant_id=1),
    MenuItem(name="Iced Green Tea Lemonade", price=4.95, calories=50, restaurant_id=1),
    MenuItem(name="Iced Peach Green Tea", price=4.95, calories=60, restaurant_id=1),
    MenuItem(name="Iced Passion Tango Tea", price=3.45, calories=0, restaurant_id=1),
    MenuItem(name="Iced Black Tea", price=3.25, calories=0, restaurant_id=1),
    MenuItem(name="Iced Green Tea", price=3.25, calories=0, restaurant_id=1),
    MenuItem(name="Iced Peach Green Tea Lemonade", price=4.75, calories=80, restaurant_id=1),
    MenuItem(name="Iced Peach Green Tea", price=4.75, calories=60, restaurant_id=1),
    MenuItem(name="Iced Black Tea Lemonade", price=4.25, calories=50, restaurant_id=1),
    MenuItem(name="Caramel Ribbon Crunch Frappuccino", price=6.75, calories=470, restaurant_id=1),
    MenuItem(name="Mocha Cookie Crumble Frappuccino", price=6.75, calories=480, restaurant_id=1),
    MenuItem(name="Strawberry Frappuccino", price=6.45, calories=370, restaurant_id=1),
    MenuItem(name="Caramel Frappuccino", price=6.45, calories=380, restaurant_id=1),
    MenuItem(name="Mocha Frappuccino", price=6.45, calories=370, restaurant_id=1),
    MenuItem(name="Coffee Frappuccino", price=6.15, calories=230, restaurant_id=1),
    MenuItem(name="Java Chip Frappuccino", price=6.45, calories=440, restaurant_id=1),
    MenuItem(name="Vanilla Bean Creme Frappuccino", price=6.15, calories=380, restaurant_id=1),
    MenuItem(name="Double Chocolaty Creme Frappuccino", price=6.45, calories=410, restaurant_id=1),
    MenuItem(name="Matcha Creme Frappuccino", price=6.45, calories=420, restaurant_id=1),
    MenuItem(name="Espresso Frappuccino", price=6.75, calories=210, restaurant_id=1),
    MenuItem(name="Peppermint Mocha Frappuccino", price=5.45, calories=430, restaurant_id=1),
    MenuItem(name="Strawberry Creme Frappuccino", price=6.25, calories=370, restaurant_id=1),
    MenuItem(name="Blueberry Scone", price=3.65, calories=380, restaurant_id=1),
    MenuItem(name="Classic Coffee Cake", price=3.95, calories=330, restaurant_id=1),
    MenuItem(name="Petite Vanilla Bean Scone", price=2.45, calories=120, restaurant_id=1),
    MenuItem(name="Old Fashioned Glazed Doughnut", price=2.95, calories=480, restaurant_id=1),
    MenuItem(name="Blueberry Muffin", price=3.95, calories=360, restaurant_id=1),
    MenuItem(name="Banana Nut Bread", price=4.65, calories=420, restaurant_id=1),
    MenuItem(name="Iced Lemon Loaf Cake", price=4.65, calories=470, restaurant_id=1),
    MenuItem(name="Pumpkin Bread", price=4.65, calories=410, restaurant_id=1),
    MenuItem(name="Butter Croissant", price=4.26, calories=260, restaurant_id=1),
    MenuItem(name="Chocolate Croissant", price=4.45, calories=340, restaurant_id=1),
    MenuItem(name="Cheese Danish", price=3.95, calories=290, restaurant_id=1),
    MenuItem(name="Plain Bagel", price=2.95, calories=280, restaurant_id=1),
    MenuItem(name="Everything Bagel", price=2.95, calories=290, restaurant_id=1),
    MenuItem(name="Avocado Spread", price=1.45, calories=90, restaurant_id=1),
    MenuItem(name="Chocolate Cake Pop", price=3.75, calories=160, restaurant_id=1),
    MenuItem(name="Chocolate Chip Cookie", price=3.25, calories=360, restaurant_id=1),
    MenuItem(name="Double Chocolate Chunk Brownie", price=3.95, calories=480, restaurant_id=1),
    MenuItem(name="Ham & Cheese Croissant", price=4.65, calories=320, restaurant_id=1),
    MenuItem(name="Marshmallow Dream Bar", price=2.50, calories=230, restaurant_id=1),
    MenuItem(name="Birthday Cake Pop", price=3.75, calories=170, restaurant_id=1),
    MenuItem(name="Classic Oatmeal", price=5.50, calories=160, restaurant_id=1),
    MenuItem(name="Cookies and Cream Cake Pop", price=3.75, calories=160, restaurant_id=1),
    MenuItem(name="Valentine Cake Pop", price=3.95, calories=140, restaurant_id=1),
    MenuItem(name="Vanilla Bean Custard Danish", price=4.25, calories=230, restaurant_id=1),
    MenuItem(name="Chicken, Maple Butter & Egg Sandwich", price=6.45, calories=420, restaurant_id=1),
    MenuItem(name="Bacon, Sausage & Egg Wrap", price=7.25, calories=640, restaurant_id=1),
    MenuItem(name="Spinach, Feta & Egg White Wrap", price=5.65, calories=290, restaurant_id=1),
    MenuItem(name="Double-Smoked Bacon, Cheddar & Egg Sandwich", price=6.45, calories=500, restaurant_id=1),
    MenuItem(name="Turkey, Bacon & Egg-White Sandwich", price=5.45, calories=230, restaurant_id=1),
    MenuItem(name="Bacon & Gruyere Egg Bites", price=5.65, calories=300, restaurant_id=1),
    MenuItem(name="Egg White & Roasted Red Pepper Egg Bites", price=5.65, calories=170, restaurant_id=1),
    MenuItem(name="Kale and Mushroom Egg Bites", price=5.65, calories=230, restaurant_id=1),
    MenuItem(name="Oleato Caffe Latte with Oatmilk", price=6.75, calories=330, restaurant_id=1),
    MenuItem(name="Iced Chai Tea Latte with Oleato Golden Foam", price=10.85, calories=510, restaurant_id=1),
    MenuItem(name="Oleato Iced Shaken Espresso with Oatmilk and Toffeenut", price=8.45, calories=360, restaurant_id=1),
    MenuItem(name="Dragon Drink Refresher with Oleato Golden Foam", price=8.95, calories=380, restaurant_id=1),
    MenuItem(name="Paradise Drink Refresher with Oleato Golden Foam", price=8.95, calories=390, restaurant_id=1),
    MenuItem(name="Iced Matcha Tea Latte with Oleato Golden Foam", price=9.25, calories=410, restaurant_id=1),
    MenuItem(name="6 inch Black Forest Ham Sub", price=5.89, calories=260, restaurant_id=2),
    MenuItem(name="6 inch All American Club Sub", price=7.69, calories=530, restaurant_id=2),
    MenuItem(name="6 inch Chicken & Bacon Ranch Melt Sub", price=6.59, calories=540, restaurant_id=2),
    MenuItem(name="6 inch Italian B.M.T Sub", price=6.49, calories=380, restaurant_id=2),
    MenuItem(name="6 inch Spicy Italian Sub", price=5.89, calories=450, restaurant_id=2),
    MenuItem(name="6 inch Steak & Cheese Sub", price=6.29, calories=340, restaurant_id=2),
    MenuItem(name="6 inch Tuna Sub", price=6.59, calories=450, restaurant_id=2),
    MenuItem(name="6 inch Meatball Marinara Sub", price=5.89, calories=430, restaurant_id=2),
    MenuItem(name="6 inch Veggie Delite Sub", price=5.29, calories=200, restaurant_id=2),
    MenuItem(name="6 inch Turkey Breast Sub", price=6.69, calories=250, restaurant_id=2),
    MenuItem(name="6 inch Roast Beef Sub", price=7.39, calories=290, restaurant_id=2),
    MenuItem(name="6 inch Rotisserie-Style Chicken Sub", price=6.19, calories=310, restaurant_id=2),
    MenuItem(name="6 inch B.L.T Sub", price=5.99, calories=340, restaurant_id=2),
    MenuItem(name="6 inch Buffalo Chicken Sub", price=6.89, calories=340, restaurant_id=2),
    MenuItem(name="6 inch Oven Roasted Turkey Sub", price=6.69, calories=260, restaurant_id=2),
    MenuItem(name="6 inch Teriyaki Chicken Sub", price=7.29, calories=353, restaurant_id=2),
    MenuItem(name="6 inch Subway Club Sub", price=6.99, calories=310, restaurant_id=2),
    MenuItem(name="6 inch Turkey B.L.T Sub", price=7.49, calories=340, restaurant_id=2),
    MenuItem(name="6 inch Cali Turkey Pro", price=8.89, calories=570, restaurant_id=2),
    MenuItem(name="6 inch The Monster", price=7.29, calories=540, restaurant_id=2),
    MenuItem(name="6 inch The Philly", price=6.69, calories=480, restaurant_id=2),
    MenuItem(name="6 inch The Outlaw", price=6.69, calories=440, restaurant_id=2),
    MenuItem(name="6 inch The Boss", price=7.59, calories=580, restaurant_id=2),
    MenuItem(name="6 inch The Mexicali", price=6.99, calories=540, restaurant_id=2),
    MenuItem(name="6 inch The Great Garlic", price=7.19, calories=570, restaurant_id=2),
    MenuItem(name="6 inch Titan Turkey", price=6.89, calories=490, restaurant_id=2),
    MenuItem(name="6 inch Garlic Roast Beef", price=7.79, calories=480, restaurant_id=2),
    MenuItem(name="6 inch The Beast", price=7.39, calories=730, restaurant_id=2),
    MenuItem(name="6 inch Grand Slam Ham", price=6.89, calories=416, restaurant_id=2),
    MenuItem(name="12 inch Black Forest Ham Sub", price=8.89, calories=520, restaurant_id=2),
    MenuItem(name="12 inch All American Club Sub", price=12.29, calories=890, restaurant_id=2),
    MenuItem(name="12 inch Sweet Onion Chicken Teriyaki Sub", price=11.39, calories=650, restaurant_id=2),
    MenuItem(name="12 inch Chicken & Bacon Ranch Melt Sub", price=12.79, calories=1070, restaurant_id=2),
    MenuItem(name="12 inch Veggie Delite Sub", price=7.69, calories=390, restaurant_id=2),
    MenuItem(name="12 inch Roast Beef Sub", price=10.39, calories=570, restaurant_id=2),
    MenuItem(name="12 inch Rotisserie-Style Chicken Sub", price=11.29, calories=630, restaurant_id=2),
    MenuItem(name="12 inch Buffalo Chicken Sub", price=10.59, calories=690, restaurant_id=2),
    MenuItem(name="12 inch Subway Melt Sub", price=10.19, calories=750, restaurant_id=2),
    MenuItem(name="12 inch Oven Roasted Turkey Sub", price=10.19, calories=530, restaurant_id=2),
    MenuItem(name="12 inch VegiMax Sub", price=8.39, calories=1040, restaurant_id=2),
    MenuItem(name="12 inch Subway Club Sub", price=10.29, calories=890, restaurant_id=2),
    MenuItem(name="12 inch The Monster", price=11.79, calories=1460, restaurant_id=2),
    MenuItem(name="12 inch The Philly", price=10.49, calories=1369, restaurant_id=2),
    MenuItem(name="12 inch The Outlaw", price=10.49, calories=1120, restaurant_id=2),
    MenuItem(name="12 inch The Boss", price=11.99, calories=1120, restaurant_id=2),
    MenuItem(name="12 inch The Great Garlic", price=12.59, calories=1290, restaurant_id=2),
    MenuItem(name="12 inch Titan Turkey", price=9.29, calories=980, restaurant_id=2),
    MenuItem(name="12 inch Garlic Roast Beef", price=11.09, calories=630, restaurant_id=2),
    MenuItem(name="12 inch The Beast", price=11.89, calories=1460, restaurant_id=2),
    MenuItem(name="12 inch Grand Slam Ham", price=9.29, calories=1000, restaurant_id=2),
    MenuItem(name="12 inch Tuna Bacon Guacamole", price=9.19, calories=1300, restaurant_id=2),
    MenuItem(name="12 inch Mexicali", price=12.39, calories=1140, restaurant_id=2),
    MenuItem(name="12 inch Supreme Meats", price=11.99, calories=900, restaurant_id=2),
    MenuItem(name="12 inch Turkey Breast Sub", price=10.19, calories=510, restaurant_id=2),
    MenuItem(name="Chipotle Southwest Steak & Cheese Wrap", price=9.69, calories=740, restaurant_id=2),
    MenuItem(name="B.L.T. Wrap", price=7.29, calories=600, restaurant_id=2),
    MenuItem(name="Black Forest Ham Wrap", price=8.89, calories=440, restaurant_id=2),
    MenuItem(name="Buffalo Chicken Wrap", price=10.59, calories=540, restaurant_id=2),
    MenuItem(name="Chicken Bacon Ranch Wrap", price=12.59, calories=800, restaurant_id=2),
    MenuItem(name="Cold Cut Combo Wrap", price=8.99, calories=560, restaurant_id=2),
    MenuItem(name="Meatball Marinara Wrap", price=8.99, calories=790, restaurant_id=2),
    MenuItem(name="Roast Beef Wrap", price=10.39, calories=490, restaurant_id=2),
    MenuItem(name="Rotisserie-Style Chicken Wrap", price=11.29, calories=680, restaurant_id=2),
    MenuItem(name="Steak & Cheese Wrap", price=9.69, calories=560, restaurant_id=2),
    MenuItem(name="Subway Club Wrap", price=10.99, calories=490, restaurant_id=2),
    MenuItem(name="Sweet Onion Chicken Teriyaki Wrap", price=11.39, calories=540, restaurant_id=2),
    MenuItem(name="Tuna Wrap", price=10.19, calories=820, restaurant_id=2),
    MenuItem(name="Turkey Breast Wrap", price=10.19, calories=430, restaurant_id=2),
    MenuItem(name="Veggie Delite Wrap", price=7.69, calories=330, restaurant_id=2),
    MenuItem(name="Black Forest Ham Chopped Salad", price=8.19, calories=120, restaurant_id=2),
    MenuItem(name="Oven Roasted Turkey Chopped Salad", price=8.99, calories=110, restaurant_id=2),
    MenuItem(name="Roast Beef Chopped Salad", price=9.69, calories=150, restaurant_id=2),
    MenuItem(name="Rotisserie-Style Chicken Chopped Salad", price=8.49, calories=170, restaurant_id=2),
    MenuItem(name="All American Club Chopped Salad", price=9.99, calories=230, restaurant_id=2),
    MenuItem(name="Sweet Onion Chicken Teriyaki Chopped Salad", price=9.59, calories=240, restaurant_id=2),
    MenuItem(name="Veggie Delite Chopped Salad", price=7.59, calories=60, restaurant_id=2),
    MenuItem(name="Chicken Bacon Ranch Chopped Salad", price=8.89, calories=460, restaurant_id=2),
    MenuItem(name="Cold Cut Combo Chopped Salad", price=8.19, calories=180, restaurant_id=2),
    MenuItem(name="Steak & Cheese Chopped Salad", price=8.59, calories=210, restaurant_id=2),
    MenuItem(name="Tuna Chopped Salad", price=8.89, calories=310, restaurant_id=2),
    MenuItem(name="Meatball Marinara Chopped Salad", price=8.19, calories=300, restaurant_id=2),
    MenuItem(name="Chips", price=1.39, calories=130, restaurant_id=2),
    MenuItem(name="Cookie", price=0.99, calories=200, restaurant_id=2),
    
]
db_session.add_all(menuItems)
db_session.commit()